# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  targetFolderPath : /home/ppp/GL3Project/Back/main
  containerImage : gl3project-back-main
  System.Debug : true
  Agent : OnPermAgent

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: $(Agent)
    steps:

    - task: SSH@0
      displayName: 'Archive files'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'cd $(System.DefaultWorkingDirectory) && zip -r main.zip .'
        readyTimeout: '20000'

    - task: SSH@0
      displayName: 'Create folder'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'mkdir -p $(targetFolderPath)'
        readyTimeout: '20000'

    - task: CopyFilesOverSSH@0
      displayName: 'Copy files to VM'
      inputs:
        sshEndpoint: 'pppVM'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: 'main.zip'
        targetFolder: '$(targetFolderPath)'
        cleanTargetFolder: true
        cleanHiddenFilesInTarget: true
        readyTimeout: '20000'

    - task: SSH@0
      displayName: 'Unzip files'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'unzip -o $(targetFolderPath)/main.zip -d $(targetFolderPath)'
        readyTimeout: '20000'

    - task: SSH@0
      displayName: 'Remove zip file'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'rm -rf $(targetFolderPath)/main.zip'
        readyTimeout: '20000'

    - task: SSH@0
      displayName: 'Build image'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'docker build --progress=plain -f $(targetFolderPath)/Dockerfile -t $(containerImage):latest $(targetFolderPath)'
        readyTimeout: '20000'
      continueOnError: true

    - task: SSH@0
      displayName: 'Remove files'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'rm -rf $(targetFolderPath)'
        readyTimeout: '20000'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: newAgent
    steps:
    - task: SSH@0
      displayName: 'Stop and remove old container'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'docker stop $(containerImage) && docker rm $(containerImage)'
        readyTimeout: '20000'
      continueOnError: true

    - task: SSH@0
      displayName: 'Run new container'
      inputs:
        sshEndpoint: 'pppVM'
        runOptions: 'commands'
        commands: 'docker run --name $(containerImage) --restart unless-stopped -d -p 80:80 $(containerImage):latest'
        readyTimeout: '20000'
