# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gl3project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://gl3project.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_1cdc889560b54125a0925ce6261b261c }}
          password: ${{ secrets.AzureAppService_ContainerPassword_1f7dffb584614e3091b0a2808f92c695 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gl3project.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cdc889560b54125a0925ce6261b261c }}/gl3project:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: FrodeHus/azwebapp-container-action@v1
        with:
          webapp_name: nestproject
          resource_group : gl3-project
          image: gl3project.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cdc889560b54125a0925ce6261b261c }}/gl3project:${{ github.sha }}
          tag: ${{ github.sha }}
          registry: gl3project
          tenant : dbd6664d-4eb9-46eb-99d8-5c43ba153c61
          service_principal: 095bfc0d-3dac-4521-a6c6-4c7179850255
          service_principal_password: 3zO8Q~Mo6NXUXdBRXIKR8GJTCvYonDJAtKC-EbDS



